/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interactive_digital_journal_gui_final;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;

/**
 *
 * @author Hp
 */
public class Add_Journal extends javax.swing.JFrame {

    /**
     * Creates new form Add_Journal
     */
    public static int flag=0;
    public Add_Journal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addcontent = new javax.swing.JTextArea();
        addtitle = new javax.swing.JTextField();
        ina = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add_Journal");
        setBackground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(800, 800));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(242, 236, 222));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Title:");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 52, -1));

        addcontent.setBackground(new java.awt.Color(242, 236, 222));
        addcontent.setColumns(20);
        addcontent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addcontent.setRows(5);
        jScrollPane1.setViewportView(addcontent);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 140, 460, 470));

        addtitle.setBackground(new java.awt.Color(242, 236, 222));
        addtitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(addtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 460, -1));

        ina.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ina.setForeground(new java.awt.Color(51, 51, 51));
        ina.setText("o");
        jPanel1.add(ina, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 580, 37, -1));

        jButton1.setBackground(new java.awt.Color(242, 236, 222));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Dashboard");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        jButton2.setBackground(new java.awt.Color(242, 236, 222));
        jButton2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 620, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\Oishee\\2nd year 1st sem\\java\\Interactive_Digital_Journal_GUI_final\\src\\Icon\\nam2.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\Oishee\\2nd year 1st sem\\java\\Interactive_Digital_Journal_GUI_final\\src\\Icon\\nam2.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 839, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        String title = addtitle.getText();
        String content = addtitle.getText();
        Date currentDate = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String date = dateFormat.format(currentDate);
        String username = ina.getText();

        String url = "jdbc:mysql://localhost/nomi";
        String user = "root";
        String pass = "Oishee_363";
        try (Connection connection = DriverManager.getConnection(url, user, pass)) {
            String sql = "INSERT INTO Journal (username, title, content) VALUES (?, ?, ?)";
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.setString(1, username);
            statement.setString(2, title);
            statement.setString(3, content);
            statement.executeUpdate();
            System.out.println("Data inserted successfully.");
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
//        Welcome dashboard = new Welcome();
//        dashboard.setVisible(true);
//        dashboard.pack();
//        dashboard.setLocationRelativeTo(null);
//        dashboard.jLabel2.setText(ina.getText());
//        ina.setText(dashboard.jLabel2.getText());
//        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        String title = addtitle.getText();
//        String content = addcontent.getText();
//        Date currentDate = new Date();
//        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
//        String date = dateFormat.format(currentDate);
//        String username = ina.getText();
//
//        String url = "jdbc:mysql://localhost/nomi";
//        String user = "root";
//        String pass = "Oishee_363";
//        try (Connection connection = DriverManager.getConnection(url, user, pass)) {
//            String sql = "INSERT INTO Journal (username, title, content,date) VALUES (?, ?, ?, ?)";
//            PreparedStatement statement = connection.prepareStatement(sql);
//            statement.setString(1, username);
//            statement.setString(2, title);
//            statement.setString(3, content);
//            statement.setString(4, date);
//            statement.executeUpdate();
//            System.out.println("Data inserted successfully.");
//        } catch (SQLException e) {
//            e.printStackTrace();
//        }
//        Welcome dashboard = new Welcome();
//        dashboard.setVisible(true);
//        dashboard.pack();
//        dashboard.setLocationRelativeTo(null);
//        dashboard.jLabel2.setText(username);
//        
//        this.dispose();
        String title = addtitle.getText();
        String content = addcontent.getText();
        Date currentDate = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String date = dateFormat.format(currentDate);
        String username = ina.getText();

        String url = "jdbc:mysql://localhost/nomi";
        String user = "root";
        String pass = "Oishee_363";

        try (Connection connection = DriverManager.getConnection(url, user, pass)) {
            String sql = "INSERT INTO Journal (username, title, content, date) VALUES (?, ?, ?, ?)";
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.setString(1, username);
            statement.setString(2, title);
            statement.setString(3, content);
            statement.setString(4, date);
            if(flag==0)
            {
                statement.executeUpdate();
                System.out.println("Data inserted successfully.");
            }
            
            

            Welcome dashboard = new Welcome();
            dashboard.setVisible(true);
            dashboard.pack();
            dashboard.setLocationRelativeTo(null);
            dashboard.jLabel2.setText(username);

            try {
                String sql2 = "SELECT DISTINCT title FROM Journal WHERE username = ?";
                PreparedStatement statement2 = connection.prepareStatement(sql2);
                statement2.setString(1, username);
                ResultSet resultSet2 = statement2.executeQuery();

                DefaultTableModel model = (DefaultTableModel) dashboard.tableclient.getModel(); 

                while (resultSet2.next()) {
                    String dashboardTitle = resultSet2.getString("title");
                    model.addRow(new Object[]{dashboardTitle});
                }
            } catch (SQLException e) {
                System.out.println("Failed to retrieve data from the database."); 
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here: save e click korse
        flag=1;
        String title = addtitle.getText();
        String content = addcontent.getText();
        Date currentDate = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String date = dateFormat.format(currentDate);
        String username = ina.getText();

        String url = "jdbc:mysql://localhost/nomi";
        String user = "root";
        String pass = "Oishee_363";

        try (Connection connection = DriverManager.getConnection(url, user, pass)) {
            String sql = "INSERT INTO Journal (username, title, content, date) VALUES (?, ?, ?, ?)";
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.setString(1, username);
            statement.setString(2, title);
            statement.setString(3, content);
            statement.setString(4, date);
            statement.executeUpdate();
            System.out.println("Data inserted successfully.");
        } catch (SQLException e) {
            e.printStackTrace();
            
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Journal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Journal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Journal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Journal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Journal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addcontent;
    private javax.swing.JTextField addtitle;
    public javax.swing.JLabel ina;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
